# Generated by Django 4.2.6 on 2023-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product')),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=100)),
                ('cat', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Shoes'), (3, 'Clothes')], verbose_name='category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
